Repository OCA/connector-telephony, pull requests merged in 2019-07, with the labels that each got.

#191 [ADD] connector_voicent
  connector_voicent/README.rst
  connector_voicent/__init__.py
  connector_voicent/__manifest__.py
  connector_voicent/data/ir_cron.xml
  connector_voicent/examples/voicent.py
  connector_voicent/models/__init__.py
  connector_voicent/models/backend_voicent.py
  connector_voicent/models/backend_voicent_call_line.py
  connector_voicent/models/backend_voicent_time_line.py
  connector_voicent/models/res_partner.py
  connector_voicent/readme/CONFIGURATION.rst
  connector_voicent/readme/CONTRIBUTORS.rst
  connector_voicent/readme/DESCRIPTION.rst
  connector_voicent/readme/ROADMAP.rst
  connector_voicent/readme/USAGE.rst
  connector_voicent/security/ir.model.access.csv
  connector_voicent/static/description/icon.png
  connector_voicent/static/description/index.html
  connector_voicent/tests/__init__.py
  connector_voicent/tests/test_backend_voicent.py
  connector_voicent/views/backend_voicent.xml
  connector_voicent/views/backend_voicent_call_line.xml
  connector_voicent/views/res_partner.xml
  oca_dependencies.txt
Labels: approved, needs review

#194 [FIX] connector_voicent: _run_update_next_call()
  connector_voicent/models/backend_voicent.py
Labels: bug

#195 [IMP] connector_voicent: Timezone
  connector_voicent/models/backend_voicent.py
Labels: approved, enhancement, needs review

#198 [FIX] connector_voicent: Documentation
  connector_voicent/readme/USAGE.rst
Labels: needs review

#196 [FIX] asterisk_click2dial: Travis errors
  asterisk_click2dial/scripts/set_name_agi.py
Labels: needs review

#199 [IMP] connector_voicent: Use Voicent-Python lib
  connector_voicent/__manifest__.py
  connector_voicent/examples/voicent.py
  connector_voicent/readme/INSTALL.rst
  requirements.txt
Labels: approved, enhancement, needs review
