Repository OCA/connector-telephony, pull requests merged in 2024-05, with the labels that each got.

#321 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .oca_hooks.cfg
  .pre-commit-config.yaml
  base_phone/i18n/de.po
  base_phone/i18n/sl.po
  base_phone/i18n/tr.po
Labels: help wanted, needs review, bot is merging ⏳

#320 [17.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .ruff.toml
  base_phone/models/phone_common.py
Labels: help wanted, needs review, bot is merging ⏳

#319 [16.0] [MIG] asterisk_click2dial: Migration to 16.0
  asterisk_click2dial/README.rst
  asterisk_click2dial/__init__.py
  asterisk_click2dial/__manifest__.py
  asterisk_click2dial/controller.py
  asterisk_click2dial/demo/asterisk_click2dial_demo.xml
  asterisk_click2dial/i18n/am.po
  asterisk_click2dial/i18n/asterisk_click2dial.pot
  asterisk_click2dial/i18n/bg.po
  asterisk_click2dial/i18n/ca.po
  asterisk_click2dial/i18n/de.po
  asterisk_click2dial/i18n/el_GR.po
  asterisk_click2dial/i18n/es.po
  asterisk_click2dial/i18n/es_AR.po
  asterisk_click2dial/i18n/es_ES.po
  asterisk_click2dial/i18n/fi.po
  asterisk_click2dial/i18n/fr.po
  asterisk_click2dial/i18n/gl.po
  asterisk_click2dial/i18n/hr.po
  asterisk_click2dial/i18n/it.po
  asterisk_click2dial/i18n/nl_BE.po
  asterisk_click2dial/i18n/pt.po
  asterisk_click2dial/i18n/pt_BR.po
  asterisk_click2dial/i18n/pt_PT.po
  asterisk_click2dial/i18n/sl.po
  asterisk_click2dial/i18n/tr.po
  asterisk_click2dial/models/__init__.py
  asterisk_click2dial/models/asterisk_server.py
  asterisk_click2dial/models/phone_common.py
  asterisk_click2dial/models/res_users.py
  asterisk_click2dial/readme/CONTRIBUTORS.rst
  asterisk_click2dial/readme/DESCRIPTION.rst
  asterisk_click2dial/requirements.txt
  asterisk_click2dial/scripts/odoo_popup_timeout.sh
  asterisk_click2dial/scripts/set_name_agi.py
  asterisk_click2dial/scripts/set_name_incoming_timeout.sh
  asterisk_click2dial/scripts/set_name_outgoing_timeout.sh
  asterisk_click2dial/security/asterisk_security.xml
  asterisk_click2dial/security/ir.model.access.csv
  asterisk_click2dial/static/description/icon.png
  asterisk_click2dial/static/description/index.html
  asterisk_click2dial/static/description/sshot-click2dial.jpg
  asterisk_click2dial/static/description/sshot-open_calling_party.jpg
  asterisk_click2dial/static/src/components/asterisk_click2dial/asterisk_click2dial.esm.js
  asterisk_click2dial/static/src/components/asterisk_click2dial/asterisk_click2dial.xml
  asterisk_click2dial/static/src/scss/asterisk.scss
  asterisk_click2dial/views/asterisk_server.xml
  asterisk_click2dial/views/res_users.xml
  requirements.txt
  setup/asterisk_click2dial/odoo/addons/asterisk_click2dial
  setup/asterisk_click2dial/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#317 [17.0] [MIG] asterisk_click2dial: Migration to 17.0
  asterisk_click2dial/README.rst
  asterisk_click2dial/__init__.py
  asterisk_click2dial/__manifest__.py
  asterisk_click2dial/controller.py
  asterisk_click2dial/demo/asterisk_click2dial_demo.xml
  asterisk_click2dial/i18n/am.po
  asterisk_click2dial/i18n/asterisk_click2dial.pot
  asterisk_click2dial/i18n/bg.po
  asterisk_click2dial/i18n/ca.po
  asterisk_click2dial/i18n/de.po
  asterisk_click2dial/i18n/el_GR.po
  asterisk_click2dial/i18n/es.po
  asterisk_click2dial/i18n/es_AR.po
  asterisk_click2dial/i18n/es_ES.po
  asterisk_click2dial/i18n/fi.po
  asterisk_click2dial/i18n/fr.po
  asterisk_click2dial/i18n/gl.po
  asterisk_click2dial/i18n/hr.po
  asterisk_click2dial/i18n/it.po
  asterisk_click2dial/i18n/nl_BE.po
  asterisk_click2dial/i18n/pt.po
  asterisk_click2dial/i18n/pt_BR.po
  asterisk_click2dial/i18n/pt_PT.po
  asterisk_click2dial/i18n/sl.po
  asterisk_click2dial/i18n/tr.po
  asterisk_click2dial/models/__init__.py
  asterisk_click2dial/models/asterisk_server.py
  asterisk_click2dial/models/phone_common.py
  asterisk_click2dial/models/res_users.py
  asterisk_click2dial/pyproject.toml
  asterisk_click2dial/readme/CONTRIBUTORS.md
  asterisk_click2dial/readme/DESCRIPTION.md
  asterisk_click2dial/requirements.txt
  asterisk_click2dial/scripts/odoo_popup_timeout.sh
  asterisk_click2dial/scripts/set_name_agi.py
  asterisk_click2dial/scripts/set_name_incoming_timeout.sh
  asterisk_click2dial/scripts/set_name_outgoing_timeout.sh
  asterisk_click2dial/security/asterisk_security.xml
  asterisk_click2dial/security/ir.model.access.csv
  asterisk_click2dial/static/description/icon.png
  asterisk_click2dial/static/description/index.html
  asterisk_click2dial/static/description/sshot-click2dial.jpg
  asterisk_click2dial/static/description/sshot-open_calling_party.jpg
  asterisk_click2dial/static/src/components/asterisk_click2dial/asterisk_click2dial.esm.js
  asterisk_click2dial/static/src/components/asterisk_click2dial/asterisk_click2dial.xml
  asterisk_click2dial/static/src/scss/asterisk.scss
  asterisk_click2dial/views/asterisk_server.xml
  asterisk_click2dial/views/res_users.xml
  requirements.txt
Labels: approved, bot is merging ⏳
